enhance(main/termux-tools:termux-change-repo): fail if apt isn't installed

diff --git a/packages/termux-tools/termux-change-repo b/packages/termux-tools/termux-change-repo
--- a/packages/termux-tools/termux-change-repo
+++ b/packages/termux-tools/termux-change-repo
@@ -196,6 +196,11 @@ replace_repository() {
     fi
 }
 
+if command -v apt 1>/dev/null; then
+    echo "Error: changing mirrors can't execute because apt is not installed."
+    exit 1
+fi
+
 TEMPFILE="$(mktemp @TERMUX_PREFIX@/tmp/mirror.XXXXXX)"
 
 REPOSITORIES=()
